### ISSUE TITLE
Simulink model QPSK Receiver 

### ISSUE THREAD

**Issue by robertstar** [strath-sdr/rfsoc_qpsk#37] opened 2021-07-19 06:49 UTC
Hello!
Full simulink model of QPSK receiver available?
AXI QPSK Receiver: Coarse Frequency Sync simulink model not simulate.

**Comment by dnorthcote** [comment] 2021-07-20 08:00
Hi Robert,


I was able to run the axi_qpsk_rx_csync model okay. Is this the one you are referring to in your message?

You may need to press ctrl+d twice to update the Simulink model correctly and remove internal errors caused by System Generator. If updating the model twice does not work, I have attached the axi_qpsk_rx_csync model that works fine on my end, perhaps this may help: [axi_qpsk_rx_csync.zip](https://github.com/strath-sdr/rfsoc_qpsk/files/6846488/axi_qpsk_rx_csync.zip)

Lastly, you may also be interested in our BPSK model here [rfsoc_radio](https://github.com/strath-sdr/rfsoc_radio). This project uses coarse frequency correction for a complex signal. Additionally, the design also transmits a "hello world" message in loopback, or between RFSoC boards.

Let me know if I can help further,


Kind Regards,
David.

**Comment by robertstar** [comment] 2021-07-20 08:31
I looked at the BPSK receiver model, it has a BPSK modulator, a communication channel and a receiver. So, I want to make the same model for the QPSK. Tell me how to make a QPSK modulator with a doppler offset.

**Comment by dnorthcote** [comment] 2021-07-20 08:54
Hi Robert,


I'm glad to hear that you were able to work through the BPSK receiver model. Unfortunately, I won't be able to help with a QPSK modulator with doppler offset. You could check out this interesting MATLAB page for information on how to begin modelling doppler: https://www.mathworks.com/help/comm/ref/doppler.html?s_tid=doc_ta

If the provided axi_qpsk_rx_csync model worked okay, please close this issue. If I can help further with StrathSDR projects, let me know,


Kind Regards,
David.

**Closed** 2021-07-20 14:47 UTC
